### DISCUSSION TITLE
How can I build it using docker?

### DISCUSSION THREAD

**Discussion by maximkrouk** [antfu/vitesse#295] [Q&A] [answered]
I anyone has a working Dockerfile, I'd be happy if you could share it, otherwise I'll probably share my Dockerfile here when I figure out how to implement it 🙂

**Comment by maximkrouk** [comment, marked as answer]
I'll use this prototype for now

`Dockerfile`
```dockerfile
FROM node:16

WORKDIR /app

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

# Files required by pnpm install
COPY .npmrc package.json pnpm-lock.yaml .

RUN pnpm install --frozen-lockfile --prod
RUN pnpm install esbuild

# Bundle app source
COPY . .

EXPOSE 8080

CMD ["pnpm", "prod"]
```

`docker-compose.yml`
```yaml
version: '3.7'

# dont know if it's needed, took the template from vapor (server-side swift framework)
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  frontend:
    image: capturecontext-frontend:latest
    build:
      context: capturecontext-frontend
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    command: ["pnpm", "prod"]
```

And I also added `"prod": "vite --port 8080 --host"` to `package.json` "scripts" section.
