### ISSUE TITLE
Catch all route doesn't return 404 status code

### ISSUE THREAD

**Issue by Rigo-m** [antfu/vitesse#342]
https://vitesse.netlify.app/asdfasf -> document returns 200, not 404

**Comment by flapili** [comment]
It's a server side configuration

example of config for netlify :
```toml
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
```

result : (using httpie)
```
$ https flapili.fr --print=h
HTTP/1.1 200 OK
[...]

$ https flapili.fr/abc --print=h
HTTP/1.1 404 Not Found
[...]
```
